export const SIP_STATUS_DISCONNECTED = "DISCONNECTED";
export const SIP_STATUS_CONNECTING = "CONNECTING";
export const SIP_STATUS_CONNECTED = "CONNECTED";
export const SIP_STATUS_REGISTERED = "REGISTERED";
export const SIP_STATUS_ERROR = "ERROR";

export const WS_STATUS_CONNECTING = "CONNECTING";
export const WS_STATUS_CONNECTED = "CONNECTED";
export const WS_STATUS_DISCONNECTED = "DISCONNECTED";

export const SIP_ERROR_TYPE_CONFIGURATION = "sipErrorType/CONFIGURATION";
export const SIP_ERROR_TYPE_CONNECTION = "sipErrorType/CONNECTION";
export const SIP_ERROR_TYPE_REGISTRATION = "sipErrorType/REGISTRATION";

export const CALL_STATUS_IDLE = "IDLE";
export const CALL_STATUS_STARTING = "STARTING";
export const CALL_STATUS_PROGRESS = "PROGRESS";
export const CALL_STATUS_FAILED = "FAILED";
export const CALL_STATUS_ENDED = "ENDED";
export const CALL_STATUS_CONFIRMED = "CONFIRMED";
export const CALL_STATUS_STOPPING = "callStatus/STOPPING";

export const CALL_DIRECTION_INCOMING = "callDirection/INCOMING";
export const CALL_DIRECTION_OUTGOING = "callDirection/OUTGOING";
